- name: Install dependencies and setup Grafana
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - wget

    - name: Create directory for Grafana keyrings
      file:
        path: /etc/yum/keyrings/
        state: directory

    - name: Add Grafana repository
      shell: |
        sudo tee /etc/yum.repos.d/grafana.repo <<EOF
        [grafana]
        name=grafana
        baseurl=https://packages.grafana.com/oss/rpm
        repo_gpgcheck=1
        enabled=1
        gpgcheck=1
        gpgkey=https://packages.grafana.com/gpg.key
        sslverify=1
        EOF

    - name: Update package list
      yum:
        name: "*"
        state: latest

    - name: Install Grafana
      yum:
        name: grafana
        state: present

    - name: Start Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes

- name: Install Prometheus
  hosts: all
  become: yes
  tasks:
    - name: Download Prometheus tarball
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.51.2/prometheus-2.51.2.linux-amd64.tar.gz
        dest: /tmp/prometheus-2.51.2.linux-amd64.tar.gz

    - name: Extract Prometheus tarball
      unarchive:
        src: /tmp/prometheus-2.51.2.linux-amd64.tar.gz
        dest: /opt/
        remote_src: yes
