- name: Install dependencies and setup Grafana
  hosts: all
  become: yes
  tasks:
    - name: Install dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - yum-utils
        - wget

    - name: Create directory for Grafana keyrings
      file:
        path: /etc/yum/keyrings/
        state: directory

    - name: Add Grafana repository
      shell: |
        sudo tee /etc/yum.repos.d/grafana.repo <<EOF
        [grafana]
        name=grafana
        baseurl=https://packages.grafana.com/oss/rpm
        repo_gpgcheck=1
        enabled=1
        gpgcheck=1
        gpgkey=https://packages.grafana.com/gpg.key
        sslverify=1
        EOF

    - name: Update package list
      yum:
        name: "*"
        state: latest

    - name: Install Grafana
      yum:
        name: grafana
        state: present

    - name: Start Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes

---
- name: Install Prometheus
  hosts: all
  become: yes
  tasks:
    - name: Install wget
      yum:
        name: wget
        state: present

    - name: Download Prometheus
      shell: wget https://github.com/prometheus/prometheus/releases/download/v2.30.1/prometheus-2.30.1.linux-amd64.tar.gz

    - name: Extract Prometheus
      shell: tar xvfz prometheus-*.tar.gz

    - name: Move Prometheus directory
      shell: mv prometheus-* /opt/prometheus

    - name: Copy Prometheus configuration
      copy:
        src: prometheus.yml
        dest: /opt/prometheus/prometheus.yml

    - name: Start Prometheus
      shell: /opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml
